version: '3.8'

services:
  ragchatbot:
    build: .
    container_name: ragchatbot-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - QDRANT_URL=http://qdrant-dbd:6333
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - COLLECTION_NAME=${COLLECTION_NAME}
      - ROUTING_COLLECTION_NAME=${ROUTING_COLLECTION_NAME}
      - MODEL_NAME=${MODEL_NAME}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL}
      - GOOGLE_DRIVE_FOLDER_ID=${GOOGLE_DRIVE_FOLDER_ID}
      - GOOGLE_SERVICE_ACCOUNT_FILE=/app/service-account.json
      - SCHEDULER_INTERVAL_HOURS=${SCHEDULER_INTERVAL_HOURS}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - LANGSMITH_PROJECT=${LANGSMITH_PROJECT}
      - LANGSMITH_TRACING=${LANGSMITH_TRACING}
    volumes:
      - ./app/data:/app/app/data:Z
      - ./logs:/app/logs:Z
      - ./service-account.json:/app/service-account.json:ro
      - chat_sessions:/tmp/chat_sessions
    depends_on:
      - qdrant
    networks:
      - ragchatbot-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    user: "1000:1000"

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-dbd
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    networks:
      - ragchatbot-network

volumes:
  qdrant_data:
  chat_sessions:

networks:
  ragchatbot-network:
    driver: bridge
